#!/bin/sh

fetchjoke() {
    curl -sH "Accept: text/plain" https://icanhazdadjoke.com/ |
        sed 's/\? /\?\n/' | sed 's/\. /\.\n/' >~/.cache/dadjoke
}

if iconf -i dadjoke; then
    # fetch random dad joke
    if ! [ -e ~/.cache/dadjoke ]; then
        fetchjoke
    fi
    (sleep 2 && fetchjoke &)

    MESSAGE="$(cat ~/.cache/dadjoke)"
elif [ "$1" = "message" ]; then
    # manual message
    MESSAGE=$(echo "" | instantmenu -p "leave message")
    [ -z "$MESSAGE" ] && exit
    shift
else
    # default
    MESSAGE="locked, enter password for $(whoami)"
fi

# deacivate 5 second screen timeout after unlock
instantlock -m "${@:-$MESSAGE}" && xset -dpms
