#!/bin/sh

# enter message manually
if [ "$1" = "message" ]; then
    DADJOKE=$(echo "" | instantmenu -p "leave message")
    shift
    
    if [ -z "$DADJOKE" ]; then
        DADJOKE="locked, enter password for $(whoami)"
    fi

else
    # fetch random dad joke
    (sleep 2 && curl -sH "Accept: text/plain" https://icanhazdadjoke.com/ |
        sed 's/\? /\?\n/' | sed 's/\. /\.\n/' >~/.cache/dadjoke) &

    DADJOKE="$(cat ~/.cache/dadjoke)"
fi

# deacivate 5 second screen timeout after unlock
instantlock -m "${@:-$DADJOKE}" && xset -dpms
